### PR TITLE
added heroku API key

### PR DESCRIPTION
**Pull request by SeanWallach**

### CODE REVIEW

**Comment by AjFroster** [comment]
Hey this was setup on travisCI.org. Can you possibly setup on .com... .org is schedule to shutdown soon. It'd be a bummer if that happened mid project

**Comment by SeanWallach** [comment]
> Hey this was setup on travisCI.org. Can you possibly setup on .com... .org is schedule to shutdown soon. It'd be a bummer if that happened mid project

Will do

**Comment by SeanWallach** [comment]
Changed setup to travisCI.com as requested.

**Review by EverettSoldaat — APPROVED** [review]
Looks good!

**Pull request merged**
