### PR TITLE
Images on homepage esoldaat

### PR DESCRIPTION
**Pull request by EverettSoldaat**
Got the images added to the User Homepage, and the Edit Book page.

Only concern is that my AWS is not happy that I have the credentials publicly accessible.  In the future I will need to replace the ones in the code with another config file that we will all need to gitignore, But it should be fine until Friday.

### CODE REVIEW

**Comment by AjFroster** [comment]
looks good, any way to initialize a book with an image already in the library just for demo purposes? I know we comment it out, but good to have a book there just in case.

**Comment by EverettSoldaat** [comment]
> looks good, any way to initialize a book with an image already in the library just for demo purposes? I know we comment it out, but good to have a book there just in case.

I could probably do that by manually adding an image to the S3 bucket and then create a new constructor where we can copy the URL.  But i think it would just be easier to upload a book using the form ahead of the demo, and it should stay there since the deployment database  has the 'update' policy instead of 'create-drop'

**Comment by AjFroster** [comment]
Good!

**Review by adybka — APPROVED** [review]
Looks good, there is some commented out code, make sure you just remove that in future commits instead of just commenting it out

**Review by AjFroster — COMMENTED** [review]
Looks good officially.

**Pull request merged**
