### PR TITLE
Add Edit Feature for owners on book

### LINKED ISSUE #25: Add 'Edit Information' feature to books that Owner has published
On page that displays all the books the owner has created, there should be the ability to edit the information of a particular book.

### LINKED ISSUE #38: Implement Owner home directory page

### LINKED ISSUE #42: User creation creates new owner not a user

### PR DESCRIPTION
**Pull request by adybka**

### CODE REVIEW

**Review by AjFroster — COMMENTED** [review]
It looks good
What I'm confused about is the conflict in the userController? I don't see anything there that should conflict. But fix that and then merging should be fine.

**Comment by adybka** [comment]
@Ajfoster4444 it was just when you made the change the main, it was slightly weird to what i had

**Comment by AjFroster** [comment]
Looks good to me

**Comment by AjFroster** [comment]
Hey in UserController you changed the userCreate function to Owner create, why?

**Review by SeanWallach — APPROVED** [review]
looks good

**Pull request merged**
