### PR TITLE
Add to cart ajfoster

### LINKED ISSUE #24: Add Book to Cart, and Purchase Book Method Implementation.
Implement a way to add a book from the browsing page to your cart, and then purchase the book.(browsing and add to Cart)

### LINKED ISSUE #42: User creation creates new owner not a user

### PR DESCRIPTION
**Pull request by AjFroster**
You can now add a Book Type to a current clients cart.

### CODE REVIEW

**Comment by AjFroster** [comment]
Hey I don't know why these builds are failing the tests, would this have something to do with the new local databases we setup?
They pass all Junit tests and it works fine on my local.

**Comment by SeanWallach** [comment]
is there no error message in travisCI? @Ajfoster4444

**Comment by SeanWallach** [comment]
all 3 of your commits failed travisCI btw

**Comment by AjFroster** [comment]
It has something to do with the deployment permissions/credentials I think, it is refering to aws. I'm unsure

**Comment by SeanWallach** [comment]
Can you post the error message to discord pls

**Comment by AjFroster** [comment]
it's linked on here in the details of the fail but ok.

**Comment by AjFroster** [comment]
fixed the issue, I had pushed the application.properties file used for postgreSQL by accident, I had it in my .gitignore file but I had pushed a version before I made that change. Branch should work on host now.

**Comment by SeanWallach** [comment]
sounds good, can you resolve the conflicts before we merge

**Comment by SeanWallach** [comment]
looks good!

**Review by EverettSoldaat — APPROVED** [review]
Looks good

**Pull request merged**
