### PR TITLE
Final cart, with quantities

### PR DESCRIPTION
**Pull request by AjFroster**
Adds quantities to the cart

### CODE REVIEW

**Review by adybka — APPROVED** [review]
Much good, changes fix, wow job

**Comment by AjFroster** [comment]
tanks

**Comment by adybka** [comment]
[Previous Pull](https://github.com/SeanWallach/SYSC-4806/pull/55) This branch is the updated fixed one

**Review by EverettSoldaat — APPROVED** [review]
Looks good

**Pull request merged**
